### ISSUE TITLE
Training module for Intents

### ISSUE THREAD

**Issue by vmugra** [buerokratt/Training-Module#10]
AS A Chatbot Trainer
I WANT TO create new and modify existing intents and relating functionalities
SO THAT the chatbot can be sufficiently trained

> Views: [Intents view](https://www.figma.com/proto/rILEM6rghNvTsEKJ1wyQBn/B%C3%BCrokratt?node-id=27%3A1150&starting-point-node-id=1%3A2)
> Files: **rasa-ilmateenused/data/nlu/** each file ending with "nlu.yml" is a separate intent file
> See [temporary list of API endpoints](https://github.com/buerokratt/Buerokratt-onboarding/issues/8)

### Acceptance Criteria

- [ ] #44
- [ ] #11
- [x] Limit example length
- [ ] Intent release ban if the minimum amount of examples is not exceeded
- [ ] Ban adding duplicate intents and examples
- [ ] #42
- [ ] Search and sort intents
- [ ] Display and add new entities (list of entities in the model) - from domain.yml file
- [x] #49
- [ ] Common intent view for common topics by using endpoints from https://github.com/buerokratt/Training-Module/issues/50
- [ ] Add new or delete common examples (deleted examples will be commented out) based on #44
- [ ] Two separate views for common intents and local intents, where common intents could not be added but can be modified (examples can be added/modified/deleted as well as switched off from the model) and local intents can be added and modified.
- [ ] #25 
- [ ]  #24 
- [ ] #107

>  For local intents if user is adding a new intent, they must choose if the local data is private/sensitive or public data (no sensitive information)

#### GUI

- [x] #53
- [x] #54
- [x] #55
- [x] #56
- [x] #73 

#### DSL

- [x] #74
- [ ] #76
- [ ] #77
- [ ] #78
- [x] #79
- [ ] #80
- [x] #49
- [ ] Search intents by using #77
- [ ] #75
- [ ] #25 

#### Integration

All of the following must be done via appropriate Ruuter endpoints

- [ ] Fetch a list of intents
- [ ] Fetch a list of contents of a specific intent
- [ ] Update a specific example of an intent
- [ ] Delete a specific example of an intent
- [ ] Delete a specified intent
- [ ] Upload examples for an intent
- [ ] Download examples of an intent
- [ ] Remove from the model

**Comment by ceirowe** [comment]
@turnerrainer 
GUI endpoints:
- Add endpoint for requesting all intents
- Add endpoint for requesting intent examples
- Add endpoint for creating a new intent
- Add endpoint for deleting an existing intent
- Add endpoint for updating an intent
- Add endpoint for updating an example
- Add endpoint for deleting an example
- Add endpoint for adding an intent to model
- Add endpoint for removing an intent from a model

PS! All these endpoints should apply to both common and local intents separately

**Comment by vmugra** [comment]
Prototype:

![Image](https://user-images.githubusercontent.com/46499312/213656045-f4a76382-e43a-4231-b566-d7fbb503f97a.png)

**Comment by ceirowe** [comment]
@vmugra GUI AC-s are in-review. This task can be moved forward aswell.

**Comment by RaulAltmae** [comment]
Done in subtasks

**Comment by KasparMinn** [comment]
PR: https://github.com/buerokratt/Training-Module/pull/270

This pull request finalizes the add, update, and delete intents functionality in the training module. 

On any one of those processes, the request sent from the front-end remains relatively simple while Ruuter will have to work through a relatively long DSL that makes several different calls between the file system, OpenSearch, and Database, all of which need to remain in the same state to avoid errors. 

To accomplish this, most processes are also checked and validated before happening, which adds to the complexity of the request. This also means that, depending on the server load, requests will usually take between 1 to 5 seconds and front-end is not updated instantly until they are completed, which is why some changes were made in the GUI, particularly the optimization of the page as well as changing the order of things happening on the screen between the start, load, and completion of requests. Additionally, added a small new component, LoadingDialogue, a simpler derivative of the regular Dialogue (no new imports used), which can be used anywhere in the application.

In addition to that, fixed some console inconsistencies and bugs regarding file deletion without changing the processes already working elsewhere in the module.

- Simplified and optimized front-end 
- Added a separate delete-intent script 
- Added a LoadingDialogue component 
- Added OpenSearch checks & calls in DSL files
- Added Database checks & calls in DSL files
- Fixed a bug with empty Intent (without examples)
- Fixed several deletion and file check bugs
