### ISSUE TITLE
Module for REGEX and Entities mapping

### ISSUE THREAD

**Issue by vmugra** [buerokratt/Training-Module#107]
AS AN NLP Trainer
I WANT TO describe entities and regex rules
SO THAT I could use them appropriately

### Acceptance Criteria

> Proto - http://proto.we.ee/burokratt/treening/treening/teemade-jareltreenimine

**Entities**

- [x] List all entities (domain.yml)
- [x] Add new, modify or delete entities (check dependecies)
- [x] Show dependencies with intents

**REGEX**

- [x] List all regexes (regex.yml)
- [x] Add new REGEX based on entities
- [x] Modify and delete REGEX (no dependencies)
- [x] Add examples and delete examples for REGEXes

##### Entities

- [x] #120
- [x] #121
- [x] #122
- [x] #123

#### Regex

- [x] #124
- [x] #325
- [x] #125
- [x] #128
- [x] #129 
- [x] #334 
- [x] #338 
- [x] #339

**Comment by RaulAltmae** [comment]
Done in subtasks

**Comment by turnerrainer** [comment]
New grooming needed due to pre-production integration developments.

**Comment by ExiRain** [comment]
There are 2 components were displayed Regexes and Entities. By one of the last changes Entities component was commented/removed. They look scimilar but their buttons function differently (add/update) i need to know which of these(or both) should be displayed.Currently Regexes(add button adds one from dropdown of existing ones) not allowing manually add new entitites and therefore i think it should be there?

**Comment by Kristjan259** [comment]
@ExiRain I think you are right in you interpretation. We cannot add, modify or delete entities (requierment specified under "Entities") from a drop down menu so therefore both views should be present.

**Comment by ExiRain** [comment]
Entities part is GUI to Ruuter is now communicating and updating Domain.yml file, missing opensearch pipeline

**Comment by ffrose** [comment]
BUG - 
Unable to add, delete or edit new and existing entities and regexes.
![image](https://github.com/buerokratt/Training-Module/assets/119657383/827aff08-a738-4898-80df-1fd836680899)

**Comment by ExiRain** [comment]
Yes, currently working on it.Had to revert some changes done by other developer so it would display properly again.
And checked that locally works but deployed have different response, currently investigating.

[Pull request](https://github.com/buerokratt/Training-Module/pull/309)

**Comment by ExiRain** [comment]
[Pull request](https://github.com/buerokratt/Training-Module/pull/349) to fix csv file upload/download.
