### ISSUE TITLE
REST service to delete an existing Rasa entity

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#123]
AS AN Architect
I WANT TO have a REST service to delete an existing Rasa entity
SO THAT there wouldn't be any duplicate services for it

### Acceptance Criteria

- [ ] Use POST endpoint `/rasa/entities/delete` to delete an existing Rasa entity
- [ ] Only proceed if #127 responds with `HTTP 200`; and
- [ ] Only proceed if #125 with input `examples=false` responds with `HTTP 200`; and
- [ ] Only proceed if #126 with input `examples=false` responds with `HTTP 200`
- [ ] Apply changes on `entities` section of [Rasa `domain.yml`](https://github.com/buerokratt/Training-Module/blob/main/mock1/domain.yml#L14-L15)

### Examples

Input `domain.yml`

```yaml
entities:
  - asukoht
  - nimi
  - aadress
```

Output after a request to delete "nimi"

```yaml
entities:
  - asukoht
  - aadress
```

**Comment by janyprus** [comment]
sample input for /rasa/entities/delete
```json
{
    "entity_name": "nimi"
}
```

**Comment by turnerrainer** [comment]
@janyprus please link this issue with an appropriate pull request.

**Comment by janyprus** [comment]
Pull request #179

**Comment by ExiRain** [comment]
Pull request : [254](https://github.com/buerokratt/Training-Module/pull/254)
Currently working but Ruuter causing sometimes a bug when guard is failing, this issue is being handled.

**Comment by turnerrainer** [comment]
Blocked due to #289

**Comment by Kristjan259** [comment]
Gives 300 error code when trying to delete an existing entitiy
