### ISSUE TITLE
Module for NLU Model analysis and evaluation

### ISSUE THREAD

**Issue by vmugra** [buerokratt/Training-Module#15]
AS AN Analyst
I WANT TO compare and evaluate trained models
SO THAT I can choose model to be released (live model)

Acceptance Criteria

- [ ] #19
- [ ] Display rasa test results for each model trained and tested https://github.com/buerokratt/Training-Module/issues/3
- [ ] Compare results for selected models
- [ ] Train new models
- [ ] Save trained model version and training time
- [ ] Search and sort models - -  update:_no searching needed only deleting!_ Sorting -> descending by training date and time
- [ ] Release (live) selected model
- [ ] Undo all data changes until selected model - versioning (GUI puudu)
- [ ] Show last changes view
- [ ] Send message/notice if new models have been trained/added -  update:_no notices needed date when trained is displayed_ 
- [ ] If last training has been unsuccessful, send error message

### GUI

- [x] #62
- [x] #63
- [x] #64

#### DSL

- [ ] #131
- [ ] #132
- [ ] #133

> ???????

#62 
- [ ] Get models

#63 
- [ ] Get specific model results from intent_report file
https://koodivaramu.eesti.ee/buerokratt/plug-and-play/rasa-ppa/-/blob/main/results/last_model_20220502/intent_report.json

#64 
- [ ] Get models results
https://koodivaramu.eesti.ee/buerokratt/plug-and-play/rasa-ppa/-/blob/main/results/last_model_20220502/

**Comment by RaulAltmae** [comment]
Done in subtasks

**Comment by turnerrainer** [comment]
New grooming needed due to pre-production integration developments.
