### ISSUE TITLE
Module for historical conversations

### ISSUE THREAD

**Issue by vmugra** [buerokratt/Training-Module#17]
AS A Chatbot Tainer
I WANT TO train data based on historical conversations
SO THAT I can add new real-life based training data

> https://www.figma.com/proto/rILEM6rghNvTsEKJ1wyQBn/B%C3%BCrokratt?node-id=280%3A8083&starting-point-node-id=1%3A2

> [Ajaloolised vestlused vaade - UXUI tba](https://www.figma.com/proto/rILEM6rghNvTsEKJ1wyQBn/B%C3%BCrokratt?node-id=27%3A1150&starting-point-node-id=1%3A2)

### Acceptance Criteria

- [ ] #9 
- [ ] Chosen samples can be used to create new [Rasa examples](https://rasa.com/docs/rasa/nlu-training-data#training-examples)
- [ ] Chosen samples can be used to create new [Rasa responses](https://rasa.com/docs/rasa/responses)
> - [ ] Create test-stories based on happy path conversation (where bot has answered and ended the story) - obsolete!
> - [ ] Display confidence scores and initiated stories/rules within conversations (Is it in the logs @vmugra?) - obsolete! let's use flagging instead

- [ ] Trained datasets end up in Document Store
- [x] Trainer datasets end up in Rasa models

#### GUI:

- [x] #70
- [x] #69

#### DSL

- [x] Use #79 to add new Rasa examples
- [x] Use #92 to create new Rasa responses
- [x] Use #1 for trained datasets to end up in Document Store
- [x] Use #28 for trainer datasets to end up in Rasa models

**Comment by turnerrainer** [comment]
@turnerrainer 2 of the remaining ACs are internal.

**Comment by turnerrainer** [comment]
Done a while ago.

**Comment by turnerrainer** [comment]
Blocked due to Ruuter responding with `HTTP 300`
