### ISSUE TITLE
GUI + DSL integration of Training Module

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#191]
AS A Product Owner of Training Module
I WANT its GUI and DSL to be fully integrated
SO THAT I could take Training Module into use in production

### Acceptance Criteria

- [ ] Work based on epics marked as `Integration` in https://github.com/orgs/buerokratt/projects/13/views/15
- [ ] See https://github.com/orgs/buerokratt/projects/13/views/7 for reference in DSL-based developments
- [ ] Specific AC described under every issue that needs GUI and DSL integration 
- [ ] https://github.com/buerokratt/Buerokratt-onboarding/issues/8 contains a list of Training Module-related endpoints
- [ ] Set up GUI based on https://github.com/buerokratt/Training-Module/tree/main/GUI
- [ ] Set up GUI based on https://github.com/buerokratt/Training-Module/tree/main/DSL
- [ ] Separate branch for every integration
- [ ] Pull requests for every integration right after being done

#### GUI

- [ ] Replace current `PATCH` GUI [MSW](https://mswjs.io) requests with `POST` and `GET` requests to appropriate Ruuter endpoints
- [ ] Use left menu from https://github.com/buerokratt/cvi

**Comment by turnerrainer** [comment]
On hold, waiting for a new partner.

**Comment by Kristjanmn** [comment]
With PR #206 all requests go to Ruuter endpoint.

**Comment by RayDNoper** [comment]
ETA 12h, partly due to still onboarding.

**Comment by turnerrainer** [comment]
New grooming needed due to pre-production integration developments.
