### ISSUE TITLE
Manage RASA 2-step fallback policy

### ISSUE THREAD

**Issue by vmugra** [buerokratt/Training-Module#26]
AS A Chatbot Trainer
I WANT TO manage fallback policies in my model
SO THAT I could setup model failure thresholds

### **Acceptance Criteria:**
- [ ] Set fallback policy thresholds
- [ ] See fallback script (RASA custom action python script)
- [ ] Manage 2-step fallback via GUI

**DSL Story's:**
- [ ] tba
- [ ] tba

**Comment by turnerrainer** [comment]
@vmugra should it be done via GUI or straight into YAML?

**Comment by turnerrainer** [comment]
@vmugra is this obsolete?

**Comment by vmugra** [comment]
Obsolete, closed task
