### ISSUE TITLE
Integration layer to use NLP intents as triggers to initiate Services

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#397]
> Linked to https://github.com/buerokratt/Training-Module/issues/362

AS A Customer Support Agent (CSA)
I WANT TO define intents in Training Module that would trigger specified Services
SO THAT I could automate same type of responses that would otherwise require repetitive manual interaction

AS A Service Manager
I WANT TO trigger specific Services when appropriate intents are detected
SO THAT I could provide e-Services to End Clients based on their NL input

AS A Product Owner
I WANT TO be confident that using intents as triggers to initiate Services would follow a certain protocol
SO THAT this wouldn't be done too easily and change too often based on how different CSA's see fit at any given time

### Acceptance Criteria

- [ ] Any CSA with appropriate permissions can propose any intent to be linked as triggers to initiate specific Services
- [ ] Any Service Manager with appropriate permissions can propose any Service to be initiated by any intent
- [ ] Both CSA and Service Managers can activate and deactivate links between intents and Services
- [ ] Only Administrative Users with proper permissions can change and/or confirm change propositions regarding linking intents with specific Services and vice versa

#### Prerequisites

- [ ] [Link intents with specific Services](https://github.com/buerokratt/Training-Module/issues/362)
- [ ] [Link Services with specific intents](https://github.com/buerokratt/Service-Module/issues/196)
- [ ] [Training Module](https://github.com/buerokratt/Training-Module) and [Service Module](https://github.com/buerokratt/Service-Module) use the same databases (`user_db`, `service_db` and `training_db`) on `test` environment

#### GUI

- [ ] GUI to link intents with Services are provided within the Training Module
- [ ] GUI to link Services with intents are provided within the Service Module
- [ ] No additional stand-alone GUI in scope of this issue is provided

#### DSL

- [ ] Ruuter DSL for Backoffice to make changes regarding either parties proposing linking intents and Services
- [ ] Ruuter DSL for Backoffice to confirm changes proposed regarding linking intents and Services
- [ ] Links between intents and Services are stored in Postgres
- [ ] Public Ruuter DSL to validate if detected intent should trigger a Service or not and act accordingly

#### Databases

- [ ] buerokratt/Training-Module#393

**Comment by 1AhmedYasser** [comment]
@turnerrainer @bartekpospiech @ExiRain 

The Third Prerequisite is now fulfilled on the test environment side, please contact me for databases details

**Comment by 1AhmedYasser** [comment]
@turnerrainer @ExiRain we to change the following menu path to point to a new page on service and training modules

Related to this ac `Ruuter DSL for Backoffice to confirm changes proposed regarding linking intents and Services`
