### ISSUE TITLE
Create test stories based on actual conversations

### ISSUE THREAD

**Issue by vmugra** [buerokratt/Training-Module#4]
AS A Service Manager
I WANT TO use actual conversations as a base to create new test stories
SO THAT they would fit with reality

### Acceptance Criteria

- [ ] Fetch a list of Rasa rules and stories with links to test stories
- [ ] Fetch the content of a test story of a chosen Rasa rule if the test story exists
- [ ] Fetch the content of a test story of a chosen Rasa story if the test story exists
- [ ] Fetch the content of the chosen Rasa rule if there are no test stories related to it
- [ ] Fetch the content of the chosen Rasa story if there are no test stories related to it
- [ ] ~Samples from full conversations can be extracted by using a GUI~
- [ ] Fetch a list of Rasa intents for the specified rule
- [ ] Fetch a list of Rasa intents for the specified story
- [ ] Create a new Rasa test story
- [ ] Update chosen existing Rasa test story
- [ ] Chosen samples can be used to create new [Rasa test stories](https://rasa.com/docs/rasa/testing-your-assistant/)
- [ ] Chosen samples can be validated against chosen, already existing [Rasa test stories](https://rasa.com/docs/rasa/testing-your-assistant/)

#### GUI

- [x] #61

#### DSL

> Linked task - https://github.com/buerokratt/Training-Module/issues/61
> Proto can be found from http://proto.we.ee/burokratt/treening/mudelipank-ja-analuutika/testlood

- [ ] #116
- [x] #108
- [ ] Use POST endpoint `/rasa/test-stories` to fetch the content of a test story of a chosen Rasa rule if the test story exists
- [ ] Use POST endpoint `/rasa/test-stories` to fetch the content of a test story of a chosen Rasa story if the test story exists
- [ ] Use POST endpoint `/rasa/rules` to fetch the content of the chosen Rasa rule if there are no test stories related to it
- [ ] Use POST endpoint `/rasa/stories` to fetch the content of the chosen Rasa story if there are no test stories related to it
- [ ] Use POST endpoint `/intents/examples` to fetch a list of Rasa intents for the specified rule
- [ ] Use POST endpoint `/intents/examples` to fetch a list of Rasa intents for the specified story
- [ ] Use #118 to create a new Rasa test story
- [ ] Use #117 to update an existing Rasa test story
- [ ] #119

> Endpoints below read data from OpenSearch

- [ ] REST endpoint `/rasa/rules` to fetch a list of [Rasa rules](https://koodivaramu.eesti.ee/buerokratt/plug-and-play/rasa-ilmateenused/-/blob/main/data/rules.yml)
- [ ] REST endpoint `/rasa/stories` to fetch a list of [Rasa stories](https://koodivaramu.eesti.ee/buerokratt/plug-and-play/rasa-ilmateenused/-/blob/main/data/stories.yml)
- [ ] REST endpoint `/rasa/stories/tests` to fetch a list of [Rasa test stories](https://koodivaramu.eesti.ee/buerokratt/plug-and-play/rasa-ilmateenused/-/tree/main/tests)
- [ ] REST endpoint `/rasa/stories/tests` with `story_name` as POST body

**Comment by RaulAltmae** [comment]
REST endpoint should be defined as Collection. `/rasa/rules` `/rasa/stories` `/rasa/stories/tests`

**Comment by RaulAltmae** [comment]
Done in subtasks

**Comment by turnerrainer** [comment]
New grooming needed due to pre-production integration developments.

**Comment by rasmusei** [comment]
@turnerrainer, is this in correct state?
