### ISSUE TITLE
REST service to delete an existing Rasa form

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#86]
AS AN Architect
I WANT to have a REST service to delete an existing Rasa form
SO THAT there wouldn't be duplicate services for it

### Acceptance Criteria

> Temporary list of endpoints - https://github.com/buerokratt/Buerokratt-onboarding/issues/8
> [Proto to add new Rasa forms](http://proto.we.ee/burokratt/treening/treening/vormid)

- [x] Use POST endpoint `/rasa/forms/delete` to delete an existing form
- [x] Apply changes on [Rasa domain.yml](https://github.com/buerokratt/Training-Module/blob/main/mock1/domain.yml#L41-L47)
- [x] Deleting a form is forbidden if #96 responds with `HTTP 200` for a request to find a matching form
- [x] Deleting a form is forbidden if #97 responds with `HTTP 200` for a request to find a matching form
- [ ] When deleting a form, all of its sub-content gets deleted as well
- [ ] Changes apply only in case a form with an input name provided (`form_name`) already exists
- [ ] In relation to https://github.com/buerokratt/Training-Module/issues/85

#### Example

Initial input

```yaml
forms:
  custom_fallback_form:
    required_slots:
        - affirm_deny
  direct_to_customer_support_form:
    required_slots:
        - affirm_deny
```

Output after a request to delete `custom_fallback_form`

```yaml
forms:
  direct_to_customer_support_form:
    required_slots:
        - affirm_deny
```

**Comment by RaulAltmae** [comment]
sample input for `/rasa/froms/delete` 

```json
{
  "form_name": "custom_fallback_form"
}
```

**Comment by turnerrainer** [comment]
@RaulAltmae please link this issue with an appropriate pull request.

**Comment by RaulAltmae** [comment]
Pull request https://github.com/buerokratt/Training-Module/pull/167

**Comment by ExiRain** [comment]
[Pull request](https://github.com/buerokratt/Training-Module/pull/359) with new changes.

**Comment by ValterAro** [comment]
Short summary: unable to delete a form even though it says that Form deleted. If I check the request response then it says "Can't find form to delete."
Expected result: the form should be deleted if you select yes on the notification and it is not forbidden
Real result: there is a notification saying that the form is deleted, but it is still there
How to reproduce: login and go to https://admin.dev.buerokratt.ee/training/training/forms , then try to delete the first form in the list.
Pic:


![Image](https://github.com/buerokratt/Training-Module/assets/122787093/e321d97c-11ac-4b4b-8f30-7eb332d99a0e)

**Comment by ValterAro** [comment]
Seems to work as intended!
